"""Candidate profile defaults from SCORING_RULES.md and a shared tech-skills dictionary.

These defaults drive the deterministic scorer and the mock resume parser so the whole
app behaves consistently offline.
"""
from typing import Dict, List

CANDIDATE_PROFILE: Dict[str, object] = {
    "name": "Kundan Srinivas Sakkuru",
    "target_roles": [
        "Entry-Level Software Engineer",
        "Junior Software Developer",
        "Full-Stack Developer",
        "React Developer",
        "Python Developer",
        "Flutter Developer",
        "Mobile App Developer",
        "Backend Developer",
        "Data Engineer",
        "AI/ML Engineer",
    ],
    "locations": ["Remote US", "Tampa FL", "Florida", "Hybrid US"],
    "work_auth": "International student; H-1B sponsorship NOT required",
    "experience_level": "New grad / 0 professional years required",
}

# Default resume skills used when no PDF text is available / to enrich parsing.
DEFAULT_SKILLS: List[str] = [
    "Python",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "Flutter",
    "Dart",
    "FastAPI",
    "Flask",
    "SQL",
    "PostgreSQL",
    "SQLite",
    "Git",
    "Docker",
    "REST",
    "HTML",
    "CSS",
    "Java",
    "AWS",
]

# Canonical tech-skills dictionary. Keys are lowercase match tokens; values are the
# display label. Aliases let several spellings map to one canonical skill.
TECH_SKILLS: Dict[str, str] = {
    "python": "Python",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "node": "Node.js",
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "express": "Express",
    "flutter": "Flutter",
    "dart": "Dart",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "django": "Django",
    "java": "Java",
    "spring": "Spring",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "c++": "C++",
    "c#": "C#",
    ".net": ".NET",
    "ruby": "Ruby",
    "rails": "Rails",
    "php": "PHP",
    "sql": "SQL",
    "mysql": "MySQL",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "sqlite": "SQLite",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "graphql": "GraphQL",
    "rest": "REST",
    "rest api": "REST",
    "html": "HTML",
    "css": "CSS",
    "tailwind": "Tailwind",
    "sass": "Sass",
    "git": "Git",
    "github": "GitHub",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "aws": "AWS",
    "gcp": "GCP",
    "azure": "Azure",
    "terraform": "Terraform",
    "ci/cd": "CI/CD",
    "linux": "Linux",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "nlp": "NLP",
    "data engineering": "Data Engineering",
    "spark": "Spark",
    "airflow": "Airflow",
    "kafka": "Kafka",
    "etl": "ETL",
    "redux": "Redux",
    "vue": "Vue",
    "angular": "Angular",
    "firebase": "Firebase",
    "supabase": "Supabase",
    "selenium": "Selenium",
    "pytest": "pytest",
    "jest": "Jest",
}
